### ISSUE TITLE
Add password reset functionality

### ISSUE THREAD

**Issue by itsmanojb** [shubhambattoo/node-api-starter#1]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request 

* **Do you want to request a *feature* or report a *bug*?**
a Feature

* **What is the current behavior?**
Currently users can only update their current password, but there's no way to recovering it.

* **What is the expected behavior?**
There should be a functionality to reset password, say, via sending a recovery link to the registered email address.

* **What is the motivation / use case for changing the behavior?**
If user has forgotten the login password this will help users reset their password.

**Comment by itsmanojb** [comment]
A simpler way of resetting password (instead of clicking on any recovery link with some expiry token as query param) can be, sending a `Security Code` to the registered mail, which user have to enter while giving new password. This method will eliminate the complexity of handling the expiry logic for the link.

**Comment by shubhambattoo** [comment]
Something like an OTP will make things smooth. Will try and pick this one up by the weekend.
